module.exports = {
	'CAN_CREATE_USER': 1,
	'CAN_POST_ERROR': 2,
	'CAN_UPDATE_USER': 3,
	'CAN_DELETE_USER': 4,
	'CAN_LIST_ACCOUNTS': 5,
	'CAN_UPDATE_ACCOUNTS': 6,
	'CAN_DELETE_ACCOUNTS': 7,
	'CAN_CREATE_ACCOUNTS': 8,
}